[package]
name = "sonar-tools"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
async-trait.workspace = true
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
sonar-core = { path = "../sonar-core" }
thiserror.workspace = true
reqwest.workspace = true
sha2.workspace = true
zip.workspace = true
url.workspace = true
uuid.workspace = true
