use serde::{Deserialize, Serialize};
use sonar_core::{PivotGraph, ProbeDescriptor, ProbeOutput, ResultInterpretation};

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct SonarReport {
    pub title: String,
    pub generated_by: String,
    pub runs: Vec<ReportRun>,
    pub graph: PivotGraph,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct ReportRun {
    pub descriptor: ProbeDescriptor,
    pub output: ProbeOutput,
    pub interpretation: ResultInterpretation,
}

impl SonarReport {
    pub fn new(title: impl Into<String>, graph: PivotGraph) -> Self {
        Self {
            title: title.into(),
            generated_by: "SonarNwork".into(),
            runs: Vec::new(),
            graph,
        }
    }

    pub fn with_run(mut self, run: ReportRun) -> Self {
        self.runs.push(run);
        self
    }
}

impl ReportRun {
    pub fn new(
        descriptor: ProbeDescriptor,
        output: ProbeOutput,
        interpretation: ResultInterpretation,
    ) -> Self {
        Self {
            descriptor,
            output,
            interpretation,
        }
    }
}

pub fn graph_to_json(graph: &PivotGraph) -> serde_json::Result<String> {
    serde_json::to_string_pretty(graph)
}

pub fn report_to_json(report: &SonarReport) -> serde_json::Result<String> {
    serde_json::to_string_pretty(report)
}

pub fn graph_to_markdown(graph: &PivotGraph) -> String {
    let mut out = String::new();
    out.push_str("# SonarNwork Report\n\n");
    out.push_str("## Entities\n\n");

    for node in graph.nodes.values() {
        out.push_str(&format!("- `{}` ({:?})\n", node.id, node.entity.kind()));
    }

    out.push_str("\n## Edges\n\n");

    for edge in &graph.edges {
        out.push_str(&format!(
            "- `{}` --{:?}--> `{}`\n",
            edge.from, edge.relation, edge.to
        ));
    }

    out
}

pub fn report_to_markdown(report: &SonarReport) -> String {
    let mut out = String::new();
    out.push_str(&format!("# {}\n\n", report.title));
    out.push_str(&format!("Generated by: `{}`\n\n", report.generated_by));

    if report.runs.is_empty() {
        out.push_str("No probe runs are included in this report.\n\n");
    } else {
        out.push_str("## Probe Results\n\n");
        for run in &report.runs {
            out.push_str(&format!(
                "### {} (`{}`)\n\n",
                run.descriptor.name, run.descriptor.id
            ));
            if let Some(summary) = run
                .interpretation
                .summary
                .as_deref()
                .or(run.output.summary.as_deref())
            {
                out.push_str(&format!("{summary}\n\n"));
            }

            out.push_str(&format!(
                "Verdict: `{:?}` {}\n\n",
                run.interpretation.verdict.status, run.interpretation.verdict.title
            ));

            let rows = if run.interpretation.summary_rows.is_empty() {
                &run.output.summary_rows
            } else {
                &run.interpretation.summary_rows
            };
            if !rows.is_empty() {
                out.push_str("| Field | Value |\n| --- | --- |\n");
                for row in rows {
                    out.push_str(&format!(
                        "| {} | {} |\n",
                        escape_table_cell(&row.label),
                        escape_table_cell(&row.value)
                    ));
                }
                out.push('\n');
            }

            if !run.output.findings.is_empty() {
                out.push_str("Findings:\n");
                for finding in &run.output.findings {
                    out.push_str(&format!(
                        "- `{:?}` {}: {}\n",
                        finding.severity, finding.title, finding.description
                    ));
                }
                out.push('\n');
            }

            if !run.output.warnings.is_empty() {
                out.push_str("Warnings:\n");
                for warning in &run.output.warnings {
                    out.push_str(&format!("- `{}`: {}\n", warning.code, warning.message));
                }
                out.push('\n');
            }

            if !run.interpretation.next_actions.is_empty() {
                out.push_str("Next actions:\n");
                for action in &run.interpretation.next_actions {
                    out.push_str(&format!(
                        "- `{}` via `{}`\n",
                        action.label_key, action.probe_id
                    ));
                }
                out.push('\n');
            }
        }
    }

    out.push_str("## Graph\n\n");
    out.push_str(&graph_to_markdown(&report.graph));
    out
}

fn escape_table_cell(value: &str) -> String {
    value.replace('|', "\\|").replace('\n', "<br>")
}

#[cfg(test)]
mod tests {
    use sonar_core::{
        ProbeCategory, ProbeDescriptor, ProbeRisk, ProbeStatus, ResultVerdict, VerdictStatus,
    };

    use super::*;

    #[test]
    fn markdown_report_includes_summary_rows() {
        let descriptor = ProbeDescriptor {
            id: "public.egress_check".into(),
            name: "Egress IP + DNS".into(),
            description: String::new(),
            category: ProbeCategory::PublicExposure,
            status: ProbeStatus::Ready,
            risk: ProbeRisk::SafeActive,
            requirements: Vec::new(),
        };
        let output = ProbeOutput {
            summary: Some("Completed.".into()),
            summary_rows: vec![sonar_core::SummaryRow::new("Public IP", "203.0.113.1")],
            ..ProbeOutput::default()
        };
        let interpretation = ResultInterpretation {
            verdict: ResultVerdict {
                status: VerdictStatus::Ok,
                title: "This machine exits through 203.0.113.1.".into(),
                detail: None,
            },
            summary: output.summary.clone(),
            summary_rows: output.summary_rows.clone(),
            next_actions: Vec::new(),
        };
        let report = SonarReport::new("Report", PivotGraph::new()).with_run(ReportRun::new(
            descriptor,
            output,
            interpretation,
        ));

        let markdown = report_to_markdown(&report);

        assert!(markdown.contains("Public IP"));
        assert!(markdown.contains("203.0.113.1"));
        assert!(markdown.contains("Verdict"));
    }
}
